# -*- mode: ruby -*-
# vi: set ft=ruby :

# Gerardo Ocampos 2022

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.box_version = "4.0.0"
  config.vm.box_check_update = false

  config.vm.define "master" do |master|
    master.vm.hostname = "linux-master-01"
    master.vm.define "linux-master-01"

    master.vm.network "private_network", ip: "192.168.33.41"

    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  config.vm.define "slave01" do |slave1|
    slave1.vm.hostname = "linux-slave-01"
    slave1.vm.define "linux-slave-01"

    slave1.vm.network "private_network", ip: "192.168.33.42"

    slave1.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  config.vm.define "slave02" do |slave2|
    slave2.vm.hostname = "linux-slave-02"
    slave2.vm.define "linux-slave-02"

    slave2.vm.network "private_network", ip: "192.168.33.43"

    slave2.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
  sudo yum install -y yum-utils
  sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
  sudo systemctl enable --now docker
  SHELL
end
